### ISSUE TITLE
Pipeline flowchart

### ISSUE THREAD

**Issue by sdmcraft** [sdmcraft/helix-project-boilerplate#15]
This task is logged to add the flowchart capturing the complete pipeline from prompt to generated blocks.

**Comment by vnagpal81** [comment]
https://adobe-my.sharepoint.com/personal/vnagpal_adobe_com/_layouts/15/doc.aspx?sourcedoc={5304552b-27f9-4bb2-a475-a18b71d5c817}&action=edit
